package p1;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author ayush
 */
public class PayNConfirm extends javax.swing.JFrame {

    /**
     * Creates new form PayNConfirm
     */String Date,Time;
     int numSeat=0;
    float price=0;
    String movie=null;
    public PayNConfirm(String Date,String Time) {
        this.Date=Date;
        this.Time=Time;
        initComponents();
        jButton2.setEnabled(false);
        jButton2.setVisible(false);
        findSeatsNPrice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Price  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 69, 32));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("No. of seats :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 126, 32));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seats :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 69, 32));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("label3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 225, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("label 2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 225, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("label1");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 225, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 112, 44));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 112, 44));

        jLabel8.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel8.setText("PAYMENT PANEL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Print obj = new Print(Date,Time,movie);
obj.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
findSeatsNPrice();
        JOptionPane.showMessageDialog(null, "  Payment Successful                   ");
jButton2.setEnabled(true);
jButton2.setVisible(true);
jButton1.setForeground(Color.lightGray);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
private void findSeatsNPrice()
{
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    int flag=0;
    try{
      try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?" +"user=root");
    String q="select seats,nofseat,movie from ticket where id=1 and date=? and time=?";
    pst=conn.prepareStatement(q);
    pst.setString(1, Date);
    pst.setString(2, Time);
    rs=pst.executeQuery();
    String bookedSeats=null;
    while(rs.next())
    {
        bookedSeats=rs.getString("seats");
        numSeat = rs.getInt("nofseat");
//        SwingUtilities.invokeLater(() -> {
//            jLabel5.setText("");
//            jLabel7.setText("");
        jLabel5.setText(bookedSeats);
        jLabel7.setText(Integer.toString(numSeat));
//        });
        System.out.println("Seats: " + bookedSeats + " | No. of Seats: " + numSeat + " | Price: " + price);
        movie = rs.getString("movie");
    }
    if(bookedSeats==null || numSeat==0 || movie==null)
    {
        flag=1;
    }
    rs.close();
    pst.close();
 }
 catch(Exception e)
 {
     System.out.println(e);
 }
      if(flag==0)
      {
 try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?" +"user=root");
     String q="select price from id where movie=? and date=? and time=?";
     pst=conn.prepareStatement(q);
     pst.setString(1, movie);
     pst.setString(2,Date);
     pst.setString(3, Time);
     rs=pst.executeQuery();
     while(rs.next())
    {
        float onePrice = rs.getFloat("price");
        price = (float)numSeat*onePrice;
        jLabel6.setText(Float.toString(price));
    }
    rs.close();
    pst.close();
    }
 catch(Exception e)
 {
     System.out.println(e);
 }
 try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?" +"user=root");
     String q="update ticket set price = ? where id = 1 and date = ? and time = ?";
     pst=conn.prepareStatement(q);
     pst.setFloat(1, price);
     pst.setString(2,Date);
     pst.setString(3, Time);
     pst.executeUpdate();
     pst.close();
 }
 catch(Exception e)
 {
     System.out.println(e);
 }
      }
      else
      {
          flag=0;
      }
}catch(Exception e)
 {
     System.out.println(e);
 }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayNConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayNConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayNConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayNConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PayNConfirm().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
